---
- name: Download Magento in given Version
  tags: magento
  sudo: no
  when: magento_download == 'yes'
  local_action: get_url
    url=http://www.magentocommerce.com/downloads/assets/{{ magento_version }}/magento-{{ magento_version }}.tar.gz
    dest={{ magento_download_tmp_dir }}/magento-{{ magento_version }}.tar.gz
    mode=0644

- name: Extract Magento
  tags: magento
  when: magento_download == 'yes'
  local_action: unarchive
    src="{{ magento_download_tmp_dir }}/magento-{{ magento_version }}.tar.gz"
    dest={{ magento_download_tmp_dir }}

- name: Copy magento from local
  tags: magento
  when: magento_download != "yes"
  copy:
    src={{ magento_copy_local_dir }}
    dest={{ magento_install_tmp_dir }}

- name: Move to Magento-Root-Dir
  tags: magento
  synchronize:
    rsync_path="sudo rsync"
    src={{ magento_download_tmp_dir }}/magento/
    dest={{ magento_root }}/
    rsync_opts="-p,--chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo="

    #rsync_opts="--chmod=D2750,--chmod=F640"

- name: Change User
  tags: magento
  shell: "chown -R {{ magento_webuser }}:{{ magento_webgroup }} {{ magento_root }}"
  notify:
    - run magento install
    - verify permissions

- name: Create Magento-Install script
  tags: magento
  template:
    src=magento-install.j2
    dest={{ magento_install_tmp_dir }}/magento-install.sh

- name: Remove app/etc/local.xml if exists
  tags: magento
  file:
    state=absent
    path="{{ magento_root }}/app/etc/local.xml"

- name: Install Magento local.xml.template
  tags: magento
  template:
    src={{ magento_local_template|default('local.xml.template.j2') }}
    dest={{ magento_root }}/app/etc/local.xml.template

- name: Download magento patch files
  tags: magento
  with_items: magento_patch_files
  get_url:
    url={{ item.url }}
    dest={{ magento_root}}/

- name: Create patch-script
  tags: magento
  template:
    src=patch.j2
    dest={{ magento_root }}/patch.sh

- name: Apply patches
  tags: magento
  command:
    chdir={{ magento_root }} sh patch.sh

- include: "modman.yml"
  tags:
    - magento
    - modman
  when: magento_modman == "yes"
