---
- name: handle modman extensions links
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  notify: modman clean
  ignore_errors: yes
  command:
    sh {{ magento_modman_bin_dir }}/handle_extensions.sh

- name: modman clean
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  command:
    "{{ magento_modman_bin_dir }}/modman clean"
  args:
    chdir: "{{ magento_root }}"

- name: modman deploy-all
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  command:
    "{{ magento_modman_bin_dir }}/modman deploy-all --force"
  args:
    chdir: "{{ magento_root }}"

- name: modman repair
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  command:
    "{{ magento_modman_bin_dir }}/modman repair"
  args:
    chdir: "{{ magento_root }}"

- name: run magento install
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  command:
    sh {{ magento_bin_dir }}/magento-install.sh

- name: Verify user
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  file:
    state: directory
    path: "{{ magento_root }}"
    owner: "{{ magento_webuser }}"
    group: "{{ magento_webgroup }}"
    recurse: true

- name: Verify permissions
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  with_items: magento_permissions_list
  shell: >
    find . -type {{ item.type }} -exec
    chmod {{ item.mode }} {} \; ;
  args:
    chdir: "{{ item.dir }}"
