---

- name: rm links 
  shell:  rm -f {{ magento_root }}/.modman/*

- name: modman link all
  shell: 
    chdir={{ magento_root }}
    free_form=yes 
    {{ magento_modman_bin_dir }}/modman link {{item.stdout}}
  ignore_errors: yes
  with_items: magento_modman_extensions.results
  notify:
    - modman deploy-all
    - modman repair
    - modman clean
- name: modman deploy-all

  shell:
    chdir={{ magento_root }}
    free_form=yes
    {{ magento_modman_bin_dir }}/modman deploy-all --force

- name: modman repair
  shell:
    chdir={{ magento_root }}
    free_form=yes 
    {{ magento_modman_bin_dir }}/modman repair

- name: modman clean
  shell:
    chdir={{ magento_root }} 
    free_form=yes
    {{ magento_modman_bin_dir }}/modman clean
