---

- name: rm links 
  notify:
    - modman clean
  shell:  rm -f {{ magento_root }}/.modman/*

- name: modman clean
  shell:
    chdir={{ magento_root }} 
    free_form=yes
    {{ magento_modman_bin_dir }}/modman clean

- name: modman link all
  ignore_errors: yes
  with_items: magento_modman_extensions.results
  notify:
    - modman deploy-all
    - modman repair
  shell: 
    chdir={{ magento_root }}
    free_form=yes 
    {{ magento_modman_bin_dir }}/modman link {{item.stdout}}

- name: modman deploy-all
  shell:
    chdir={{ magento_root }}
    free_form=yes
    "{{ magento_modman_bin_dir }}/modman" deploy-all --force

- name: modman repair
  shell:
    chdir={{ magento_root }}
    free_form=yes 
    {{ magento_modman_bin_dir }}/modman repair

- name: run magento install
  shell: 
    free_form=yes
    sh {{ magento_install_tmp_dir }}/magento-install.sh

- name: verify permissions
  with_items: magento_permissions_list
  shell: >
    chdir={{ item.dir}} 
    free_form=yes
    chown -R {{ magento_webuser }}:{{ magento_webgroup }} {{ magento_root }};
    find . -type {{ item.type }} -exec 
    chmod {{ item.mode }} {}  
    chown {{ item.owner|default( magento_webuser ) }}:{{ item.group|default( magento_webgroup ) }} {} \; 


